export const MENU = {
    super_admin: [
        { id: 'dashboard', label: 'Dashboard', icon: 'fa-table-columns', path: '/dashboard' },
        { id: 'organizations', label: 'Organizations', icon: 'fa-building', path: '/organizations' },
        { id: 'students', label: 'Students', icon: 'fa-user-graduate', path: '/students' },
        { id: 'teachers', label: 'Teachers', icon: 'fa-chalkboard-user', path: '/teachers' },
        { id: 'parents', label: 'Parents', icon: 'fa-people-roof', path: '/parents' },
        { id: 'classes', label: 'Classes', icon: 'fa-landmark', path: '/classes' },
        { id: 'subjects', label: 'Subjects', icon: 'fa-book', path: '/subjects' },
        { id: 'attendance', label: 'Attendance', icon: 'fa-clipboard-user', path: '/attendance' },
        { id: 'exams', label: 'Exams', icon: 'fa-file-lines', path: '/exams' },
        { id: 'results', label: 'Results', icon: 'fa-ranking-star', path: '/results' },
        { id: 'fees', label: 'Fees', icon: 'fa-indian-rupee-sign', path: '/fees' },
        { id: 'payroll', label: 'Payroll', icon: 'fa-money-bill-trend-up', path: '/payroll' },
        { id: 'notices', label: 'Notices', icon: 'fa-bullhorn', path: '/notices', badge: true },
        { id: 'reports', label: 'Reports', icon: 'fa-chart-pie', path: '/reports' },
        { id: 'settings', label: 'Settings', icon: 'fa-gear', path: '/settings' },
        { id: 'audit-logs', label: 'Audit Logs', icon: 'fa-clock-rotate-left', path: '/audit-logs' },
    ],
    admin: [
        { id: 'dashboard', label: 'Dashboard', icon: 'fa-table-columns', path: '/dashboard' },
        { id: 'students', label: 'Students', icon: 'fa-user-graduate', path: '/students' },
        { id: 'teachers', label: 'Teachers', icon: 'fa-chalkboard-user', path: '/teachers' },
        { id: 'parents', label: 'Parents', icon: 'fa-people-roof', path: '/parents' },
        { id: 'classes', label: 'Classes', icon: 'fa-landmark', path: '/classes' },
        { id: 'subjects', label: 'Subjects', icon: 'fa-book', path: '/subjects' },
        { id: 'attendance', label: 'Attendance', icon: 'fa-clipboard-user', path: '/attendance' },
        { id: 'exams', label: 'Exams', icon: 'fa-file-lines', path: '/exams' },
        { id: 'results', label: 'Results', icon: 'fa-ranking-star', path: '/results' },
        { id: 'fees', label: 'Fees', icon: 'fa-indian-rupee-sign', path: '/fees' },
        { id: 'notices', label: 'Notices', icon: 'fa-bullhorn', path: '/notices', badge: true },
        { id: 'reports', label: 'Reports', icon: 'fa-chart-pie', path: '/reports' },
        { id: 'settings', label: 'Settings', icon: 'fa-gear', path: '/settings' },
    ],
    teacher: [
        { id: 'dashboard', label: 'Dashboard', icon: 'fa-table-columns', path: '/dashboard' },
        { id: 'classes', label: 'My Classes', icon: 'fa-landmark', path: '/classes' },
        { id: 'students', label: 'My Students', icon: 'fa-user-graduate', path: '/students' },
        { id: 'attendance', label: 'Attendance', icon: 'fa-clipboard-user', path: '/attendance' },
        { id: 'assignments', label: 'Assignments', icon: 'fa-book-open', path: '/assignments' },
        { id: 'exams', label: 'Exams', icon: 'fa-file-lines', path: '/exams' },
        { id: 'results', label: 'Results', icon: 'fa-ranking-star', path: '/results' },
        { id: 'notices', label: 'Notices', icon: 'fa-bullhorn', path: '/notices', badge: true },
        { id: 'timetable', label: 'Timetable', icon: 'fa-calendar-days', path: '/timetable' },
        { id: 'profile', label: 'Profile', icon: 'fa-user', path: '/profile' },
    ],
    student: [
        { id: 'dashboard', label: 'Dashboard', icon: 'fa-table-columns', path: '/dashboard' },
        { id: 'profile', label: 'My Profile', icon: 'fa-user', path: '/profile' },
        { id: 'classes', label: 'My Classes', icon: 'fa-landmark', path: '/classes' },
        { id: 'attendance', label: 'Attendance', icon: 'fa-clipboard-user', path: '/attendance' },
        { id: 'assignments', label: 'Assignments', icon: 'fa-book-open', path: '/assignments' },
        { id: 'exams', label: 'Exams', icon: 'fa-file-lines', path: '/exams' },
        { id: 'results', label: 'Results', icon: 'fa-ranking-star', path: '/results' },
        { id: 'timetable', label: 'Timetable', icon: 'fa-calendar-days', path: '/timetable' },
        { id: 'fees', label: 'Fees', icon: 'fa-indian-rupee-sign', path: '/fees' },
        { id: 'notices', label: 'Notices', icon: 'fa-bullhorn', path: '/notices', badge: true },
        { id: 'settings', label: 'Profile Settings', icon: 'fa-gear', path: '/settings' },
    ],
    parent: [
        { id: 'dashboard', label: 'Dashboard', icon: 'fa-table-columns', path: '/dashboard' },
        { id: 'students', label: 'My Children', icon: 'fa-children', path: '/students' },
        { id: 'profile', label: 'Child Profile', icon: 'fa-user', path: '/profile' },
        { id: 'attendance', label: 'Attendance', icon: 'fa-clipboard-user', path: '/attendance' },
        { id: 'assignments', label: 'Assignments', icon: 'fa-book-open', path: '/assignments' },
        { id: 'exams', label: 'Exams', icon: 'fa-file-lines', path: '/exams' },
        { id: 'results', label: 'Results', icon: 'fa-ranking-star', path: '/results' },
        { id: 'fees', label: 'Fees', icon: 'fa-indian-rupee-sign', path: '/fees' },
        { id: 'notices', label: 'Notices', icon: 'fa-bullhorn', path: '/notices', badge: true },
        { id: 'timetable', label: 'Timetable', icon: 'fa-calendar-days', path: '/timetable' },
        { id: 'settings', label: 'Profile Settings', icon: 'fa-gear', path: '/settings' },
    ],
};
